buffer_size:
  macbook: 8
  mini1: 8
  mini2: 8
  mini3: 8
  pi4: 2
  pi5: 2
  win: 1
host_ip:
  ipad: 172.20.10.3
  macbook: 10.10.0.1
  mini1: 10.10.0.1
  mini2: 10.10.0.2
  mini3: 10.10.0.3
  pi4: 10.10.0.1
  pi5: 192.168.50.1
  win: 10.10.0.1
metrics_log_interval: 50
model_name: causal_gpt2
num_layers: 6
num_nodes: 3
num_workers: 2
port:
  default: 65432
  ipad: 8000
  macbook: 65432
  mini1: 65432
  mini2: 65432
  mini3: 65432
  pi4: 65432
  pi5: 65432
  win: 65432
server: mini2
total_num_nodes: 2
track_network_metrics: true
web_interface:
  api_port: 8000
  frontend_port: 5050
workers:
  regular:
  - hostname: mini2
    rank: 0
    user: yuvrajsingh2
  - hostname: mini3
    rank: 2
    user: yuvrajsingh3
  tablets: []
